# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0149ff6b7a2defbac578dc56683db6803ed986cc3c6cffad6cf4b60341cb228ba5acbf6c1b963a99c5b78d237b50bd37e255495633b8950b64195234f1741d01

test:
  secret_key_base: cf9b15639c01f4ade3d2be04b7870293c065df22d458bffed737155098bdca30dd37588c01b8cb4b7c015f0dc094fa6bc4df4727fa143bf4d2e5737a555ca450

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
